/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_radu_gui_NativeFileDialogs */

#ifndef _Included_me_radu_gui_NativeFileDialogs
#define _Included_me_radu_gui_NativeFileDialogs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_radu_gui_NativeFileDialogs
 * Method:    selectFile
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_me_radu_gui_NativeFileDialogs_selectFile(JNIEnv * javaEnvironment, jclass obj, jstring filter);

#ifdef __cplusplus
}
#endif
#endif
